source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target "GuitarChina" do

pod 'AFNetworking', '~> 2.5'
pod 'SDWebImage'
pod 'FMDB'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'UMengSocial'
pod 'UMengAnalytics'
pod 'NJKWebViewProgress'
pod 'IQKeyboardManager'
pod 'MagicalRecord'
pod 'BlocksKit'

end

target "GuitarChinaPro" do
    
    pod 'AFNetworking', '~> 2.5'
    pod 'SDWebImage'
    pod 'FMDB'
    pod 'FDFullscreenPopGesture', '~> 1.1'
    pod 'UMengSocial'
    pod 'UMengAnalytics'
    pod 'NJKWebViewProgress'
    pod 'IQKeyboardManager'
    pod 'MagicalRecord'
    pod 'BlocksKit'
    
end