source 'https://github.com/CocoaPods/Specs.git'

pod 'AFNetworking', '~> 2.5'
pod 'SDWebImage'
pod 'FMDB'
pod "DKNightVersion", "~> 0.8.1"
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'UMengSocial'
pod 'UMengAnalytics'
pod 'NJKWebViewProgress'
pod 'IQKeyboardManager'
pod "MagicalRecord"
